name: Test canon project
on: [ push ]

jobs:
    Test-Canon:
        runs-on: archlinux
        steps:
            - name: Check out repository code
              uses: https://git.rrricardo.top/actions/checkout@v4
            - name: Cache nuget packages
              uses: https://git.rrricardo.top/actions/cache@v4
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget
                  save-always: true
            - name: Build code
              run: dotnet build
            - name: Run test code
              run: dotnet test
